# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: auto sign

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 0,12 * * *"    
  workflow_dispatch:


concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm i -g pnpm && pnpm i

      - name: Rebuild the dist/ directory
        run: |
          pnpm run build
          pnpm run package
      - name: try auto sign   
        uses: ./
        with:
          users: ${{secrets.users}}   